postgresql_global_config_options:
  - option: listen_addresses
    value: "*"
  - option: unix_socket_directories
    value: "/var/run/postgresql"

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: "10.0.0.1/24", auth_method: md5 }
