# Firewall Setup
firewall_default_input: DROP
firewall_default_output: ACCEPT
firewall_default_forward: DROP
firewall_allowed_input_tcp_ports:
  - 80
  - 443
firewall_additional_rules:
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.3 --dport 22 -j ACCEPT"
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.4 --dport 22 -j ACCEPT"
  - "iptables -t filter -A OUTPUT -p tcp -d 10.0.0.1 --dport 8006 -j ACCEPT"
