# Configure Nginx
nginx_stream_template: {}
nginx_http_template:
  default: "{{ vhost_vericonomy }}"
  vrm: "{{ vhost_vrm }}"
  vrc: "{{ vhost_vrc }}"
  administration: "{{ vhost_administration }}"
  # Redirect old domain to new one
  vericoin: "{{vhost_vericoin }}"
