#################################################################
#                  VRM.VERICONOMY DOMAIN                        #
#                                                               #
#################################################################
vhost_vrm: 
  template_file: http/custom.conf.j2
  conf_file_name: "vrm.conf"
  conf_file_location: /etc/nginx/conf.d/
  servers:
    # vrm.vericonomy.com - SSL Redirection
    vrm-ssl-redirect:
      listen:
        listen_http:
          port: 80
          ssl: false
      server_name: "vrm.vericonomy.com"
      error_page: /usr/share/nginx/html/error/_site
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://$server_name$request_uri"
    # vrm.vericonomy.com - Redirection to Vericoin.info
    vrm-ssl:
      listen:
        listen_https:
          port: 443
          ssl: true
      server_name: "vrm.vericonomy.com"
      error_page: /usr/share/nginx/html/error/_site
      autoindex: false
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://vericoin.info$request_uri"
      ssl:
        cert: "/etc/letsencrypt/live/vericonomy.com/fullchain.pem"
        key: "/etc/letsencrypt/live/vericonomy.com/privkey.pem"
        dhparam: /etc/ssl/dhparam4.pem
        protocols: TLSv1 TLSv1.1 TLSv1.2
        ciphers: HIGH:!aNULL:!MD5
        prefer_server_ciphers: true
        session_cache: shared:SSL:10m
        session_timeout: 10m
        disable_session_tickets: true
        stapling: false
        stapling_verify: false
    # explorer-vrm.vericonomy.com - SSL Redirection
    explorer-vrm-ssl-redirect:
      listen:
        listen_http:
          port: 80
          ssl: false
      server_name: "explorer-vrm.vericonomy.com"
      error_page: /usr/share/nginx/html/error/_site
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://$server_name$request_uri"
    # explorer-vrm.vericonomy.com
    explorer-vrm-ssl:
      listen:
        listen_https:
          port: 443
          ssl: true
      server_name: "explorer-vrm.vericonomy.com"
      error_page: /usr/share/nginx/html/error/_site
      autoindex: false
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
      reverse_proxy:
        locations:
          - location: /
            add_headers:
              - name: Strict-Transport-Security
                value: max-age=15768000; includeSubDomains
                always: true
              - name: X-Frame-Options
                value: SAMEORIGIN
                always: true
            proxy_set_header:
              - name: X-Real-IP
                value: $remote_addr
              - name: X-Forwarded-For
                value: $proxy_add_x_forwarded_for
              - name: X-Forwarded-Proto
                value: $scheme
            proxy_pass: http://vrm-explorer-frontend
          - location: /rest
            add_headers:
              - name: Strict-Transport-Security
                value: max-age=15768000; includeSubDomains
                always: true
              - name: X-Frame-Options
                value: SAMEORIGIN
                always: true
            proxy_set_header:
              - name: X-Real-IP
                value: $remote_addr
              - name: X-Forwarded-For
                value: $proxy_add_x_forwarded_for
              - name: X-Forwarded-Proto
                value: $scheme
            proxy_pass: http://vrm-explorer-api
            websocket: true
      ssl:
        cert: "/etc/letsencrypt/live/vericonomy.com/fullchain.pem"
        key: "/etc/letsencrypt/live/vericonomy.com/privkey.pem"
        dhparam: /etc/ssl/dhparam4.pem
        protocols: TLSv1 TLSv1.1 TLSv1.2
        ciphers: HIGH:!aNULL:!MD5
        prefer_server_ciphers: true
        session_cache: shared:SSL:10m
        session_timeout: 10m
        disable_session_tickets: true
        stapling: false
        stapling_verify: false
  upstreams:
    api:
      name: vrm-explorer-api
      lb_method: least_conn
      zone_name: frontend
      zone_size: 64k
      sticky_cookie: false
      servers:
        srv01:
          address: "10.0.0.65"
          port: 3001
          weight: 1
          health_check: max_fails=3 fail_timeout=20s
    vrm-explorer-frontend:
      name: vrm-explorer-frontend
      lb_method: least_conn
      zone_name: frontend
      zone_size: 64k
      sticky_cookie: false
      servers:
        srv01:
          address: "10.0.0.65"
          port: 3000
          weight: 1
          health_check: max_fails=3 fail_timeout=20s
