#################################################################
#                      VERICOIN DOMAIN                          #
#                                                               #
#################################################################
vhost_vericoin:
  template_file: http/custom.conf.j2
  conf_file_name: "vericoin.conf"
  conf_file_location: /etc/nginx/conf.d/
  servers:
    # veriumstats.vericoin.info - SSL Redirection
    veriumstats-redirect:
      listen:
        listen_http:
          port: 80
          ssl: false
      server_name: "veriumstats.vericoin.info"
      error_page: /usr/share/nginx/html/error/_site
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://$server_name$request_uri"
    # veriumstats.vericoin.info - Redirection to explorer-vrm.vericonomy.com
    main-ssl:
      listen:
        listen_https:
          port: 443
          ssl: true
      server_name: "veriumstats.vericoin.info"
      error_page: /usr/share/nginx/html/error/_site
      autoindex: false
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://explorer-vrm.vericonomy.com$request_uri"
      ssl:
        cert: "/etc/letsencrypt/live/veriumstats.vericoin.info/fullchain.pem"
        key: "/etc/letsencrypt/live/veriumstats.vericoin.info/privkey.pem"
        dhparam: /etc/ssl/dhparam4.pem
        protocols: TLSv1 TLSv1.1 TLSv1.2
        ciphers: HIGH:!aNULL:!MD5
        prefer_server_ciphers: true
        session_cache: shared:SSL:10m
        session_timeout: 10m
        disable_session_tickets: true
        stapling: false
        stapling_verify: false
    # slack.vericoin.info - SSL Redirection
    slack-redirect:
      listen:
        listen_http:
          port: 80
          ssl: false
      server_name: "slack.vericoin.info"
      error_page: /usr/share/nginx/html/error/_site
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://$server_name$request_uri"
    # slack.vericoin.info - Redirection to slack.vericonomy.com
    slack-ssl:
      listen:
        listen_https:
          port: 443
          ssl: true
      server_name: "slack.vericoin.info"
      error_page: /usr/share/nginx/html/error/_site
      autoindex: false
      web_server:
        http_demo_conf: false
        locations:
          - location: "^~ /.well-known/acme-challenge/"
            custom_options:
              - "allow all"
              - "default_type \"text/plain\""
              - "root /home/www/letsencrypt"
              - "break"
          - location: "/"
            custom_options:
              - "return 301 https://slack.vericonomy.com$request_uri"
      ssl:
        cert: "/etc/letsencrypt/live/veriumstats.vericoin.info/fullchain.pem"
        key: "/etc/letsencrypt/live/veriumstats.vericoin.info/privkey.pem"
        dhparam: /etc/ssl/dhparam4.pem
        protocols: TLSv1 TLSv1.1 TLSv1.2
        ciphers: HIGH:!aNULL:!MD5
        prefer_server_ciphers: true
        session_cache: shared:SSL:10m
        session_timeout: 10m
        disable_session_tickets: true
        stapling: false
        stapling_verify: false
