---
- name: Install VRC Wallet and bootstrap
  hosts: wallet_vrc
  become: yes
  tasks:
    - name: Vericoin Wallet - Install dependencies
      apt:
        name:
          - git
          - build-essential
          - libtool
          - autotools-dev
          - automake
          - pkg-config
          - libssl-dev
          - libevent-dev
          - bsdmainutils
          - python3
          - libcurl4-openssl-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-chrono-dev
          - libboost-program-options-dev
          - libboost-test-dev
          - libboost-thread-dev
          - libminizip-dev
          - zlib1g-dev
          - libprotobuf-dev
          - protobuf-compiler
          - libqrencode-dev
          - libdb-dev
          - libdb++-dev
          - unzip
          - zip
          - jq
          - rsync
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Vericoin Wallet - Clone Vericoin Wallet
      git:
        repo: https://github.com/VeriConomy/vericoin.git
        dest: "/home/vrc/wallet"
        update: no
        version: "2.0.0"
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Stat vericoin binary
      stat:
        path: "/home/vrc/wallet/src/vericoind"
      register: vericoin_build
      become: true
      become_user: vrc

    - name: Vericoin Wallet - AutoGen
      command: "./autogen.sh"
      args:
        chdir: /home/vrc/wallet
      when: vericoin_build.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Configure
      command: "./configure"
      args:
        chdir: /home/vrc/wallet
      when: vericoin_build.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Build
      make:
        chdir: /home/vrc/wallet
      when: vericoin_build.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Create wallet directory
      file:
        path: "/home/vrc/.vericonomy"
        state: directory
        owner: "vrc"
        group: "vrc"
        mode: "0775"
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Create wallet sub directory
      file:
        path: "/home/vrc/.vericonomy/vericoin"
        state: directory
        owner: "vrc"
        group: "vrc"
        mode: "0775"
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Stat vericoin bootstrap
      stat:
        path: "/home/vrc/.vericonomy/vericoin/blocks"
      register: vericoin_bootstrap
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Create bootstrap directory
      file:
        path: "/home/vrc/bootstrap"
        state: directory
        owner: "vrc"
        group: "vrc"
        mode: "0775"
      when: vericoin_bootstrap.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Download bootstrap
      unarchive:
        src: http://files.vericonomy.com/vrc/2.0/bootstrap/bootstrap.zip
        dest: /home/vrc/bootstrap
        remote_src: yes
        creates: /home/vrc/bootstrap/bootstrap/blk0001.dat
      when: vericoin_bootstrap.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Copy bootstrap to good directory
      copy:
        src: /home/vrc/bootstrap/bootstrap/
        dest: /home/vrc/.vericonomy/vericoin/
        remote_src: yes
        force: yes
      when: vericoin_bootstrap.stat.exists == false
      become: true
      become_user: vrc

    - name: Vericoin Wallet - Clean bootstrap
      file:
        state: absent
        path: /home/vrc/bootstrap/bootstrap

    - name: Vericoin Wallet - Retrieve node list
      uri:
        url: "https://chainz.cryptoid.info/explorer/peers.nodes.dws?coin=vrc&subver=%2FVeritoshi%3A1.7.2%2F"
        method: GET
        return_content: yes
      register: node_list_result

    - name: Vericoin Wallet - Write Config File
      template:
        src: templates/wallet/vericoin.conf.j2
        dest: /home/vrc/.vericonomy/vericonomy.conf
        owner: vrc
        group: vrc
        mode: '0600'
      vars:
        node_list: "{{ node_list_result.json }}"
      register: app_conf
      become: true
      become_user: vrc

    # Set vericoin service
    - name: Vericoin Wallet - Create Service
      template:
        src: templates/wallet/vericoind.service.j2
        dest: /etc/systemd/system/vericoind.service
        mode: '0644'

    # Start wallet
    - name: Vericoin Wallet - Enable and start service
      service:
        name: vericoind
        enabled: yes
        state: restarted
      when: app_conf.changed

    # Add boostrap generator if needed
    - name: Vericoin Wallet - Boostrap Generator
      block:
        - name: Vericoin Boostraper - Create scripts directory
          file:
            path: "/home/vrc/scripts"
            state: directory
            owner: "vrc"
            group: "vrc"
            mode: "0775"
          become: true
          become_user: vrc
  
        - name: Vericoin Boostraper - Copy bootstrap script
          copy:
            src: files/vrc-bootstrap.sh
            dest: /home/vrc/scripts/bootstrap.sh
            owner: vrc
            group: vrc
            mode: '0775'
  
        - name: Vericoin Boostraper - Add bootstrap generator crontab
          cron:
            name: Vericoin Bootstraper
            job: "/home/vrc/scripts/bootstrap.sh >/dev/null 2>&1"
            minute: "0"
            hour: "1"
            weekday: "0"
            user: "vrc"
      when: bootstrap_generator is defined and bootstrap_generator
