# Configure Nginx
nginx_stream_template: {}
nginx_http_template:
#################################################################
#                    FILES.VERICONOMY.COM                       #
#                                                               #
#################################################################
  files:
    template_file: http/custom.conf.j2
    conf_file_name: "files.vericonomy.conf"
    conf_file_location: /etc/nginx/conf.d/
    servers:
      files:
        listen:
          listen_http:
            port: 80
            ssl: false
        server_name: "files.vericonomy.com"
        error_page: /usr/share/nginx/html/error/_site
        autoindex: true
        root: "/home/www/vericonomy/files/"
        custom_options:
          - "disable_symlinks off"
        web_server:
          http_demo_conf: false
          locations:
            - location: "= /favicon.ico"
              allows:
              custom_options:
                - "log_not_found off"
                - "access_log off"
                - "allow all"
            - location: "~ /\\."
              custom_options:
                - "access_log off"
                - "log_not_found off"
                - "deny all"
            - location: "~ \\.(jpg|jpeg|png|gif|ico|css|js|pdf|gz)$"
              custom_options:
                - "expires 7d"
            - location: "~ \\.(zip)$"
              custom_options:
                - "expires 1d"
