- name: Virtual Host - Create files directory
  file:
    path: "/home/www/vericonomy/files"
    state: directory
    recurse: yes
    owner: "www-data"
    group: "www-data"
    mode: u=rwX,g=rX,o=rX

- name: Virtual Host - Create files directory bootstrap vrm
  file:
    path: "/home/www/vericonomy/files/vrm/bootstrap"
    state: directory
    recurse: yes
    owner: "www-data"
    group: "www-data"
    mode: u=rwX,g=rX,o=rX

- name: Virtual Host - Create files directory bootstrap vrc
  file:
    path: "/home/www/vericonomy/files/vrc/bootstrap"
    state: directory
    recurse: yes
    owner: "www-data"
    group: "www-data"
    mode: u=rwX,g=rX,o=rX

- name: Virtual Host - Change permission of files
  file:
    path: "/home/www/vericonomy/files"
    state: directory
    recurse: yes
    owner: "www-data"
    group: "www-data"
    mode: u=rwX,g=rX,o=rX

- name: Virtual Host - Create scripts directory
  file:
    path: "/opt/scripts"
    state: directory
  become: true

- name: Virtual Host - Copy sync-bootstraps vrm script
  copy:
    src: files/sync-bootstraps-vrm.sh
    dest: /opt/scripts/sync-bootstraps-vrm.sh
    owner: root
    group: root
    mode: '0755'

- name: Webserver - Add rsync vrm bootstrap crontab
  cron:
    name: Sync Bootstraps VRM
    job: "/opt/scripts/sync-bootstraps-vrm.sh"
    minute: "0"
    hour: "7"
    user: "root"

- name: Virtual Host - Copy sync-bootstraps vrc script
  copy:
    src: files/sync-bootstraps-vrc.sh
    dest: /opt/scripts/sync-bootstraps-vrc.sh
    owner: root
    group: root
    mode: '0755'

- name: Webserver - Add rsync vrc bootstrap crontab
  cron:
    name: Sync Bootstraps VRC
    job: "/opt/scripts/sync-bootstraps-vrc.sh"
    minute: "0"
    hour: "7"
    weekday: "6"
    user: "root"
