# Firewall Setup
firewall_default_input: DROP
firewall_default_output: DROP
firewall_default_forward: DROP
firewall_additional_rules:
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.3 --dport 22 -j ACCEPT"
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.4 --dport 22 -j ACCEPT"
  # EXPLORER
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.2 --dport 3000 -j ACCEPT"
  - "iptables -t filter -A INPUT -p tcp -s 10.0.0.2 --dport 3001 -j ACCEPT"
  # REDIS
  - "iptables -t filter -A OUTPUT -p tcp -d 10.0.0.30 --dport 6379 -j ACCEPT"
  # PG
  - "iptables -t filter -A OUTPUT -p tcp -d 10.0.0.20 --dport 5432 -j ACCEPT"
  # WALLET
  - "iptables -t filter -A OUTPUT -p tcp -d 10.0.0.11 --dport 58683 -j ACCEPT"
